### ISSUE TITLE
:AutoComplete on is needed even when vim.g.chaincomplete is set

### ISSUE THREAD

**Issue by tssm** [mg979/chaincomplete#1]
Maybe I'm misunderstanding the documentation, but even when I have this on my config file I need to call `:AutoComplete on` to make it work.

```
vim.g.chaincomplete = {
    autocomplete = {
        enabled = true,
        prefix = 1,
        triggers = true
    },
    chain_lsp = {"omni", "file"},
    chain_nolsp = {"omni", "file"},
    use_hover = false
}
```

Even a simple `vim.g.chaincomplete = { autocomplete = true }` fails. What am I missing?

(Let me also thank you for this plugin. I was looking for an alternative to MUcomplete for a while)

**Comment by mg979** [comment]
I haven't updated the version here for a while, I reworked a lot of stuff in the meanwhile, I'll push an update soon.

**Comment by tssm** [comment]
Awesome, thanks!

**Comment by mg979** [comment]
I updated the plugin, note that it has a dependency now, and it's not yet feature-complete, but basic stuff should work (including `:AutoComplete` command).

**Comment by Konfekt** [comment]
Would you mind expanding where mu-complete fell short and how chaincomplete overcame it?
